# Generated by Django 5.0.1 on 2024-01-09 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, verbose_name="Название")),
                ("weight", models.FloatField(verbose_name="Объем занимаемой памяти")),
                (
                    "w_type",
                    models.CharField(
                        choices=[
                            ("KB", "Килобайты"),
                            ("MB", "Мегабайты"),
                            ("GB", "Гигабайты"),
                        ],
                        default="KB",
                        max_length=2,
                        verbose_name="Тип веса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заключение",
                "verbose_name_plural": "Заключения",
            },
        ),
        migrations.CreateModel(
            name="Parametr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, verbose_name="Название")),
                ("weight", models.FloatField(verbose_name="Объем занимаемой памяти")),
                (
                    "w_type",
                    models.CharField(
                        choices=[
                            ("KB", "Килобайты"),
                            ("MB", "Мегабайты"),
                            ("GB", "Гигабайты"),
                        ],
                        default="KB",
                        max_length=2,
                        verbose_name="Тип веса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметр",
                "verbose_name_plural": "Параметры",
            },
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название системы"),
                ),
            ],
            options={
                "verbose_name": "Cистема",
                "verbose_name_plural": "Cистемы",
            },
        ),
        migrations.CreateModel(
            name="Research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, verbose_name="Название")),
                ("weight", models.FloatField(verbose_name="Объем занимаемой памяти")),
                (
                    "w_type",
                    models.CharField(
                        choices=[
                            ("KB", "Килобайты"),
                            ("MB", "Мегабайты"),
                            ("GB", "Гигабайты"),
                        ],
                        default="KB",
                        max_length=2,
                        verbose_name="Тип веса",
                    ),
                ),
                (
                    "conclusion",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="HSNData.conclusion",
                        verbose_name="Заключение",
                    ),
                ),
                (
                    "parametrs",
                    models.ManyToManyField(
                        to="HSNData.parametr", verbose_name="Список параметров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Исследование",
                "verbose_name_plural": "Исследования",
            },
        ),
        migrations.CreateModel(
            name="Organ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название Органа"),
                ),
                (
                    "systems",
                    models.ManyToManyField(to="HSNData.system", verbose_name="Системы"),
                ),
            ],
            options={
                "verbose_name": "Орган",
                "verbose_name_plural": "Органы",
            },
        ),
    ]
