# Generated by Django 5.0.1 on 2024-01-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HSNData", "0002_research_organs"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametr",
            name="is_research",
            field=models.BooleanField(
                default=True, verbose_name="Является исследованием?"
            ),
        ),
    ]
